#!/usr/bin/env bash
# configures ubuntu server to resolve local host to 127.0.0.2
#facebook.com to 8.8.8.8

cp /etc/hosts ~/newconfiguration
echo "127.0.0.2		localhost" > ~/newconfig
echo "8.8.8.8 		facebook.com" >> ~/newconfig

cp -f ~newconfig /etc/hosts
