#!/usr/bin/env bash
# Install necessary packages
sudo apt install curl gnupg2 ca-certificates lsb-release ubuntu-keyring
curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor \
    | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
gpg --dry-run --quiet --no-keyring --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" \
    | sudo tee /etc/apt/sources.list.d/nginx.list
    
echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" \
    | sudo tee /etc/apt/preferences.d/99nginx
    
sudo apt-get -y update
sudo apt-get install -y nginx

# Create Hello World HTML page
echo  "Hello World!" | /var/www/index.html >/dev/null
# Configure nginx server block to serve index.html
cat <<EOF | sudo /etc/nginx/conf.d/default.conf  > /dev/null
server {
       listen 80 default_server;
       listen [::]:80 default_server;
       
       root /usr/share/nginx/html;
       index index.html index.htm;

       location / {
       root /;
        try_files \$uri \$uri/ =404;;
       }
}
EOF

sudo systemctl start nginx
sudo nginx -s reload;


