#!/usr/bin/env bash
#install nginx, make success message "Hello world" listen at port 80
sudo apt-get -y  update
sudo apt-get install -y  nginx

mkdir -p /etc/nginx/html && touch /etc/nginx/html/index.html

#create Hello World HTML page
echo "Hello world!" > /etc/nginx/html/index.html > /dev/null

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
