#!/usr/bin/env bash
#This script installs nginx
# Install nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
# Configure nginx to listen on port 80 and serve "Hello World!" at the root
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

#file path to default config
CONFIG_FILE="/etc/nginx/sites-available/default"

#server block configuration
NEW_SERVER_BLOCK=$(cat << 'EOF'
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ = 404;
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
EOF
)
sed -i "/^server\s*{/ {:a;N;/}\s*$/!ba; s|server\s*{[^}]*}|$NEW_SERVER_BLOCK|}" "$CONFIG_FILE"
# Restart nginx
sudo service nginx restart
