#!/usr/bin/env bash
# makes /redirect_me to redirect to another page

sudo apt-get -y  update
sudo apt-get install -y  nginx

echo "Hello world!" |
    tee /etc/nginx/html/index.html /usr/share/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http:www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

# start nginx after reloading config
service nginx restart
