#!/usr/bin/env bash
# makes /redirect_me to redirect to another page

sudo apt-get -y  update
sudo apt-get install -y  nginx
mkdir -p /etc/nginx/html && touch /etc/nginx/html/index.html

echo "Hello world!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root  =7>7 /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http:www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
	root /var/www/html/404.html;
        internal;
    }

}" > /etc/nginx/sites-available/default

# start nginx after reloading config
service nginx restart
