#!/usr/bin/env bash

sudo apt-get -y  update
sudo apt-get install -y  nginx
echo "Hello world!" |sudo  tee /usr/share/nginx/html/index.html
service nginx restart
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http:www.youtube.com/watch?v=QH2-TGUlwu4;
    }
 error_page 404 /404.html;
    location /404 {
      root /usr/share/nginx/html;
      internal;
    }
}" > $CONFIG_FILE

# start nginx after reloading config
service nginx start
}" > $CONFIG_FILE

# start nginx after reloading config
service nginx start
