#! /usr/bin/env bash
#Pings an Ip address received as an argument 5 times.

if [ $# -ne 1 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

# IP address provided as an argument
ip_address="$1"

# Ping the IP address 5 times and display the result
ping -c 5 "$ip_address"
