#!/usr/bin/env bash
# configures ubuntu server to resolve local host to 127.0.0.2
#facebook.com to 8.8.8.8

cp /etc/hosts ~/configfile

sed -i 's/127.*$/127.0.0.2 localhost/' ~/configfile
echo "8.8.8.8 facebook.com" >> ~/configfile

cp -f ~/configfile /etc/hosts
